version: 1.0
publish: app
services:
  app:
    command: streamlit run genart.py
    build:
      type: dockerfile
      config: ./.runme/Dockerfile
    ports:
      - container: 8080
        public: 80
